const express = require('express');
const QuoteRequest = require('../models/QuoteRequest');
const { sendEmail } = require('../utils/email');
const adminCredentials = require('../config/adminCredentials');
const { requireAuth } = require('../middleware/auth');

const router = express.Router();

// POST /api/quotes - Create a new AI quote request and notify admin
router.post('/', async (req, res) => {
  const { prompt, quote, memberName, memberEmail } = req.body;

  if (!prompt || !quote) {
    return res.status(400).json({ success: false, error: 'Prompt and quote text are required.' });
  }

  try {
    const quoteRequest = await QuoteRequest.create({
      prompt: String(prompt).trim(),
      quote: String(quote).trim(),
      memberName: String(memberName || '').trim(),
      memberEmail: String(memberEmail || '').trim(),
      source: 'ai',
      status: 'new'
    });

    const adminEmail = adminCredentials.username;
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f4f6fb;">
        <div style="background-color: #ffffff; padding: 24px; border-radius: 12px; border: 1px solid #e5e7eb;">
          <h2 style="color: #111827;">New AI Quote Request</h2>
          <p style="color: #374151;">A new quote was generated by the AI assistant.</p>
          <p><strong>Prompt:</strong> ${quoteRequest.prompt}</p>
          <p><strong>Generated Quote:</strong></p>
          <div style="background: #f3f4f6; padding: 16px; border-radius: 10px; color: #111827;">${quoteRequest.quote}</div>
          ${quoteRequest.memberName || quoteRequest.memberEmail ? `
            <p><strong>Member:</strong> ${quoteRequest.memberName || 'Unknown'}</p>
            <p><strong>Email:</strong> ${quoteRequest.memberEmail || 'Not provided'}</p>
          ` : ''}
          <p style="font-size: 0.9rem; color: #6b7280; margin-top: 20px;">This request has been recorded in the admin dashboard.</p>
        </div>
      </div>
    `;

    await sendEmail(adminEmail, 'New AI Quote Request | Cylin Painters', htmlContent);

    res.status(201).json({ success: true, quoteRequest });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// GET /api/quotes/admin - Admin fetch quote requests
router.get('/admin', requireAuth, async (req, res) => {
  try {
    const quotes = await QuoteRequest.find().sort({ createdAt: -1 });
    res.json({ success: true, quotes });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// PUT /api/quotes/:id/status - Update quote request status from admin dashboard
router.put('/:id/status', requireAuth, async (req, res) => {
  try {
    const { status } = req.body;
    if (!['new', 'reviewed', 'closed'].includes(status)) {
      return res.status(400).json({ success: false, error: 'Invalid status value.' });
    }

    const quote = await QuoteRequest.findByIdAndUpdate(req.params.id, { status }, { new: true });
    if (!quote) {
      return res.status(404).json({ success: false, error: 'Quote request not found.' });
    }

    res.json({ success: true, quote });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

module.exports = router;
